site_name: GIS-UDM Course Plan
site_url: https://learn.kdmarc.xyz
repo_url: https://github.com/marcjazz/gis-udm

theme:
  name: shadcn
  logo: assets/logo.svg

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
  show_title: false
  show_stargazers: false
  icon: assets/logo.svg
  topbar_sections: true
  show_datetime: true

nav:
  - 'Home': 'index.md'
  - 'Linux Fundamentals':
      - 'Introduction': 'linux_fundamentals/index.md'
      - 'Package Management': 'linux_fundamentals/installation_and_pkg_mgnt/index.md'
      - 'Labs':
          - 'Lab 1': 'linux_fundamentals/labs/lab1.md'
  - 'Linux Expert':
      - 'Introduction': 'linux_expert/index.md'
      - 'Shell Scripting':
          - 'Overview': 'linux_expert/scripting/index.md'
          - 'Shell Environment': 'linux_expert/scripting/session1.md'
          - 'Scripting Intro': 'linux_expert/scripting/session2.md'
          - 'Bash Basics': 'linux_expert/scripting/session3.md'
          - 'Control Structures': 'linux_expert/scripting/session4.md'
          - 'Loops': 'linux_expert/scripting/session5.md'
          - 'Functions': 'linux_expert/scripting/session6.md'
          - 'SQL Intro': 'linux_expert/scripting/session7.md'
          - 'Process Automation': 'linux_expert/scripting/session8.md'
      - 'AI Admin': 'linux_expert/ai_in_admin/index.md'
      - 'Labs':
          - 'Lab 1': 'linux_expert/labs/scripting_lab1.md'
  - 'Virtualization Fundamentals':
      - 'Introduction': 'virtualization/index.md'
      - 'Virtualization':
          - 'Overview': 'virtualization/virtualization_fundamentals/index.md'
          - 'Virtualization Intro': 'virtualization/virtualization_fundamentals/session1.md'
          - 'Hypervisors': 'virtualization/virtualization_fundamentals/session2.md'
          - 'First VM': 'virtualization/virtualization_fundamentals/session3.md'
          - 'VM Hardware': 'virtualization/virtualization_fundamentals/session4.md'
          - 'Network Modes': 'virtualization/virtualization_fundamentals/session5.md'
          - 'Snapshots': 'virtualization/virtualization_fundamentals/session6.md'
          - 'Cloning': 'virtualization/virtualization_fundamentals/session7.md'
          - 'Automation': 'virtualization/virtualization_fundamentals/session8.md'


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
  - shadcn.extensions.codexec

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marcjazz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuidja-marco/

plugins:
  - search
  - excalidraw
  - pygments:
      light: autumn
      dark: github-dark