site_name: GIS-UDM Course Plan
site_url: https://learn.kdmarc.xyz
repo_url: https://github.com/marcjazz/gis-udm

theme:
  name: shadcn
  logo: assets/logo.svg

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
  show_title: false
  show_stargazers: false
  icon: heroicons:rocket-launch
  topbar_sections: true
  show_datetime: true

nav:
  - 'Home': 'index.md'
  - 'Linux Fundamentals':
      - 'UCC111': 'ucc111/index.md'
      - 'Linux Installation and Package Management': 'ucc111/installation_and_pkg_mgnt/index.md'
      - 'Labs':
          - 'Lab 1 - The Phoenix Server': 'ucc111/labs/lab1.md'
  - 'Linux Expert':
      - 'UCC121': 'ucc121/index.md'
      - 'Shell Scripting':
          - 'Overview': 'ucc121/scripting/index.md'
          - 'Mastering the Shell Environment': 'ucc121/scripting/session1.md'
          - 'Introduction to Scripting': 'ucc121/scripting/session2.md'
      - 'AI in Administration': 'ucc121/ai_in_admin/index.md'
      - 'Labs':
          - 'Lab 1 - Duplicate Files': 'ucc121/labs/scripting_lab1.md'
  - 'Virtualization Fundamentals':
      - 'UCC141': 'ucc141/index.md'
      - 'Virtualization Fundamentals':
          - 'Overview': 'ucc141/virtualization_fundamentals/index.md'
          - 'Hypervisors Deep Dive': 'ucc141/virtualization_fundamentals/session2.md'
          - 'Creating Your First VM': 'ucc141/virtualization_fundamentals/session3.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - shadcn.extensions.codexec

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marcjazz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marco-kuidja/

plugins:
  - search
  - excalidraw
  - pygments:
      light: autumn
      dark: github-dark